name: "sensor api"
on: 
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths:
      - Sensor_API/**
defaults: 
  run: 
    working-directory: Sensor_API

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 0 
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
         java-version: '11'
         distribution: 'adopt'
     
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Build and test project with Maven
      run: mvn -B test --file pom.xml
      
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with: 
        args: >
          -Dsonar.organization=fhict-s-siem
          -Dsonar.projectKey=S3-SiemLucassen-HAP_Sensor_API          
          -Dsonar.java.binaries=target/classes 
          -Dsonar.sources=src/main/java/
#     run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=fhict-s-siem -Dsonar.projectKey=S3-SiemLucassen-HAP_Sensor_API
